---
title: Yexancommits
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  -
    scope:
      path: "img"
    values:
      image: true
  -
    scope:
      path: "img/lolcomtest"
    values:
      lolcomtest: true
  -
    scope:
      path: "img/www.rosemood.fr"
    values:
      rosemood: true
  -
    scope:
      path: "img/sauws.best"
    values:
      sauws: true
  -
    scope:
      path: "marie"
    values:
      marie: true
plugins:
- jekyll-coffeescript
