---
title: Yexancommits
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: img
  values:
    image: true
- scope:
    path: img/lolcomtest
  values:
    lolcomtest: true
plugins:
- jekyll-coffeescript
